version: 2.1
orbs:
  cypress: cypress-io/cypress@1.8.0
jobs:
  buildIt:
    docker:
      - image: circleci/node:10.2.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
  testIt:
    - run:
      name: Run Cypress tests
      command: npx cypress run --reporter cypress-multi-reporters --reporter-options configFile=config.json
      working_directory: e2e

workflows:
  build_and_test:
    jobs:
      - buildIt
      - testIt
      # - cypress/run:
      #     requires:
      #       - buildIt
      #     working_directory: e2e
